### ISSUE TITLE
BSC Dodo

### ISSUE THREAD

**Issue by digitalftl** [yuichiroaoki/poly-flash#2]
Hi there,

I've seen that dodo has BSC pools.
Will it work If I port this contract to BSC with all the right parameters, contracts, pairs, pools and everything? 

I have my own private node on BSC.

Thank you!

**Comment by yuichiroaoki** [comment]
I guess it would. 1inch api supports bsc as well.

**Comment by digitalftl** [comment]
Do I need to deploy manually the LendingPoolAddressesProvider contract on BSC I guess, because I can't find the aave's contract on BSC. Is that right?

**Comment by yuichiroaoki** [comment]
You dont need aave's contract. You borrow tokens from dodo pools with this contract.

**Comment by bpevreall** [comment]
Is it as simple as changing entries to use BSC or is it more complicated than that?

**Comment by yuichiroaoki** [comment]
yes I suppose.

**Comment by Deadlolo** [comment]
> Is it as simple as changing entries to use BSC or is it more complicated than that?

did it worked ?
