### ISSUE TITLE
Check DODO lending pool

### ISSUE THREAD

**Issue by yuichiroaoki** [yuichiroaoki/poly-flash#3]
To prevent this issue
https://github.com/yuichiroaoki/poly-flashloan-bot/issues/9

**Comment by trancee** [comment]
In my case, it was about the `INSUFFICIENT_OUTPUT_AMOUNT`, could you also make sure this is correct?

**Comment by yuichiroaoki** [comment]
That's right. Thank you for pointing it out.

I'm going to check ```INSUFFICIENT_OUTPUT_AMOUNT``` error as well.
