### ISSUE TITLE
Can't deploy the last commit contract

### ISSUE THREAD

**Issue by h4ckm1n-dev** [yuichiroaoki/poly-flash#31]
Hello Yuichi ! i can't deploy the last commit you made ...

"yarn run deploy --netowrk polygon" doesent work neither "npx hardhat run scripts/deploy.ts --network polygon" get stuck and when i run the command from visual studio (without --network polygon) it deploy an adresse not a contract

![Capture d’écran du 2022-02-13 05-29-53](https://user-images.githubusercontent.com/97511408/153738763-0bc78414-3a12-4cb7-8294-bd19452403f8.png)
k

**Comment by Solh4ckm1n** [comment]
i thinks it create the contract but doesn't output the address because i paid Matic fr the contract creation

**Comment by Solh4ckm1n** [comment]
my bad ... when i check the adress taht deployed the contract on polygon scan i can see the contract
