### ISSUE TITLE
Error HH8

### ISSUE THREAD

**Issue by 1NF3RNVS** [yuichiroaoki/poly-flash#38]
I get this error when using Yarn compile. what is?
Error HH8: There's one or more errors in your config file:

  * Invalid value {"forking":{}} for HardhatConfig.networks.hardhat - Expected a value of type HardhatNetworkConfig.

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

For more info go to https://hardhat.org/HH8 or run Hardhat with --show-stack-traces

**Comment by iouae** [comment]
Is this an error, right?

**Comment by 1NF3RNVS** [comment]
Yes, I can't solve it, do you know how?
