### ISSUE TITLE
Error out of gas

### ISSUE THREAD

**Issue by 1NF3RNVS** [yuichiroaoki/poly-flash#39]
help what is problem?
I try to send funds to my smart contract and this error appears
https://polygonscan.com/tx/0x081b73e1c40ece1d5dd495a9f12644d09a27896767982f39cc1ff7a3f30eb3ce

**Comment by Deadlolo** [comment]
try to increase the gas limit while doing your transaction

**Comment by 1NF3RNVS** [comment]
It was in the middle, I put it high and the error continues

**Comment by 1NF3RNVS** [comment]
I send 9 matic and I get that error in alchemy polygon
"jsonrpc":"2.0"
"method":"eth_estimateGas"
"params":[
0:{
"data":NULL
"from":"0x8f4e95bea5cc0497a17be3cb35f1208fffb22a1d"
"gas":"0x1b19a4e"
"gasPrice":"0x0"
"to":"0x58af3d020f4dcc419eb339ea058edc37f9d9b6f5"
"value":"0x0"
}
]
}
