### ISSUE TITLE
Update readme. Step 4

### ISSUE THREAD

**Issue by axel2200** [yuichiroaoki/poly-flash#50]
Hi!!
Thanks for sharing the code!!

just a small comment on readme Step 4 I think it need to be update:

yarn test test/polygon/flashloan.test.ts
to
yarn test test/polygon/dodoflash.test.ts

Looks the test/polygon/flashloan.test.ts file don't exist any more.

Thanks

**Comment by yuichiroaoki** [comment]
Thank you for pointing it out!
